---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <mysql-deployment-name>
spec:
  replicas: 1
  serviceName: "<mysql-service-name>"
  selector:
    matchLabels:
      app: <mysql-deployment-name>
  template:
    metadata:
      labels:
        app: <mysql-deployment-name>
    spec:
      containers:
        - name: <container name>
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <mysql-secret-name>
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <mysql-secret-name>
                  key: mysql-user-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: <mysql-secret-name>
                  key: mysql-user-id
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: <mysql-secret-name>
                  key: mysql-database
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
