apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostconfig
data:
  database__client: mysql
  database__connection__host: mysql-service
  database__connection__user: user
  url: http://ghost.example.com
