apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-user-password: <your_secure_password>
  mysql-root-password: <your_secure_root_password>
  mysql-user-id: user
  mysql-database: mydb
