---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <ghost-psv-name>
spec:
  storageClassName: <storage-class-name>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
